export const workouts = [
  {
    title: 'Lake Inniscarra Ireland -- Pyramid',
    hasDetails: true,
    isSeries: false,
    thumb: '/ifit/lake-inniscarra-thumb.jpeg',
    trainer: '/ifit/lake-inniscarra-trainer.jpeg',
    thumbAlt: 'Lake Inniscarra',
    trainerAlt: 'Inniscarra trainer',
    time: '30:53',
    distance: '1,6428 M',
  },
  {
    title: 'Performance Series',
    hasDetails: false,
    isSeries: true,
    thumb: '/ifit/performance-series-thumb.jpeg',
    trainer: '/ifit/performance-series-trainer.jpeg',
    thumbAlt: 'some alt',
    trainerAlt: 'some trainer alt',
    number: 9,
  },
  {
    title: 'Slow Pulls and Fast Intervals',
    time: '44:13',
    distance: '9,948 M',
    hasDetails: false,
    isSeries: false,
    thumb: '/ifit/slow-pulls-thumb.jpeg',
    trainer: '/ifit/slow-pulls-trainer.jpeg',
    thumbAlt: 'some alt',
    trainerAlt: 'some trainer alt',
  },
  {
    title: '20 Minutes to Toned',
    hasDetails: false,
    isSeries: true,
    thumb: '/ifit/20-minutes-to-toned-thumb.jpeg',
    trainer: '/ifit/20-minutes-to-toned-trainer.jpeg',
    thumbAlt: 'some alt',
    trainerAlt: 'some trainer alt',
    number: 12,
  },
  {
    title: 'Charles Race, Boston, Massachusetts',
    time: '36:22',
    distance: '8,648 M',
    hasDetails: false,
    isSeries: false,
    thumb: '/ifit/charles-race-thumb.jpeg',
    trainer: '/ifit/charles-race-trainer.jpeg',
    thumbAlt: 'some alt',
    trainerAlt: 'some trainer alt',
  },
  {
    title: 'Full-Body HIIT Series',
    hasDetails: false,
    isSeries: true,
    thumb: '/ifit/full-body-hiit-thumb.jpeg',
    trainer: '/ifit/full-body-hiit-trainer.jpeg',
    thumbAlt: 'some alt',
    trainerAlt: 'some trainer alt',
    number: 12,
  },
  {
    title: 'Kafue River, Zambia -- Power Stroke Pyramid',
    time: '22:22',
    distance: '4,660 M',
    hasDetails: false,
    isSeries: false,
    thumb: '/ifit/kafue-river-thumb.jpeg',
    trainer: '/ifit/kafue-river-trainer.jpeg',
    thumbAlt: 'some alt',
    trainerAlt: 'some trainer alt',
  },
  {
    title: 'Shred and Burn Series',
    hasDetails: false,
    isSeries: true,
    thumb: '/ifit/shred-and-burn-thumb.jpeg',
    trainer: '/ifit/shred-and-burn-trainer.jpeg',
    thumbAlt: 'some alt',
    trainerAlt: 'some trainer alt',
    number: 16,
  },
]
